"""Initial

Revision ID: 6cad0931516f
Revises:
Create Date: 2020-08-02 19:50:54.463136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cad0931516f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempt_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("correct_code", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("dnv", sa.String(), nullable=True),
        sa.Column("dtnasc", sa.String(), nullable=True),
        sa.Column("client_ip", sa.String(), nullable=True),
        sa.Column("client_date_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempt_log_id"), "attempt_log", ["id"], unique=False)
    op.create_table(
        "result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("IDExport", sa.Integer(), nullable=True),
        sa.Column("Barcode", sa.String(), nullable=True),
        sa.Column("LotNumber", sa.String(), nullable=True),
        sa.Column("DataNasc", sa.String(), nullable=True),
        sa.Column("HoraNasc", sa.String(), nullable=True),
        sa.Column("DataColeta", sa.String(), nullable=True),
        sa.Column("prMotherFirstname", sa.String(), nullable=True),
        sa.Column("prMotherSurname", sa.String(), nullable=True),
        sa.Column("CPF", sa.String(), nullable=True),
        sa.Column("ptnFirstname", sa.String(), nullable=True),
        sa.Column("ptnSurname", sa.String(), nullable=True),
        sa.Column("DNV", sa.String(), nullable=True),
        sa.Column("CNS", sa.String(), nullable=True),
        sa.Column("ptnEmail", sa.String(), nullable=True),
        sa.Column("ptnPhone1", sa.String(), nullable=True),
        sa.Column("ptnPhone2", sa.String(), nullable=True),
        sa.Column("COD_LocColeta", sa.String(), nullable=True),
        sa.Column("LocalColeta", sa.String(), nullable=True),
        sa.Column("COD_HospitalNasc", sa.String(), nullable=True),
        sa.Column("HospitalNasc", sa.String(), nullable=True),
        sa.Column("LocalNasc", sa.String(), nullable=True),
        sa.Column("PDF_Filename", sa.String(), nullable=True),
        sa.Column("PDF_ImageDate", sa.DateTime(), nullable=True),
        sa.Column("FILE_EXPORT_DATE", sa.DateTime(), nullable=True),
        sa.Column("FILE_EXPORT_NAME", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("sms_sent", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_result_CNS"), "result", ["CNS"], unique=False)
    op.create_index(op.f("ix_result_CPF"), "result", ["CPF"], unique=False)
    op.create_index(op.f("ix_result_DNV"), "result", ["DNV"], unique=False)
    op.create_index(op.f("ix_result_IDExport"), "result", ["IDExport"], unique=True)
    op.create_index(op.f("ix_result_id"), "result", ["id"], unique=False)
    op.create_table(
        "templates_result",
        sa.Column("IDExport", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("IDExport", "template_id"),
    )
    op.create_table(
        "templates_sms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("msg", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_templates_sms_id"), "templates_sms", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("login", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
    )
    op.create_index(op.f("ix_user_cpf"), "user", ["cpf"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "hospital_cs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("email1", sa.String(), nullable=True),
        sa.Column("email2", sa.String(), nullable=True),
        sa.Column("email3", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hospital_cs_code"), "hospital_cs", ["code"], unique=True)
    op.create_index(op.f("ix_hospital_cs_id"), "hospital_cs", ["id"], unique=False)
    op.create_table(
        "log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("results_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("client_ip", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("client_date_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["results_id"], ["result.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_id"), "log", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_id"), table_name="log")
    op.drop_table("log")
    op.drop_index(op.f("ix_hospital_cs_id"), table_name="hospital_cs")
    op.drop_index(op.f("ix_hospital_cs_code"), table_name="hospital_cs")
    op.drop_table("hospital_cs")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_cpf"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_templates_sms_id"), table_name="templates_sms")
    op.drop_table("templates_sms")
    op.drop_table("templates_result")
    op.drop_index(op.f("ix_result_id"), table_name="result")
    op.drop_index(op.f("ix_result_IDExport"), table_name="result")
    op.drop_index(op.f("ix_result_DNV"), table_name="result")
    op.drop_index(op.f("ix_result_CPF"), table_name="result")
    op.drop_index(op.f("ix_result_CNS"), table_name="result")
    op.drop_table("result")
    op.drop_index(op.f("ix_attempt_log_id"), table_name="attempt_log")
    op.drop_table("attempt_log")
    # ### end Alembic commands ###
